// Used in all forms, safe to always include
Vue.component("CHeader", Header);
Vue.component("CRow", Row);
Vue.component("CPage", Page);
Vue.component("CField", Field);
Vue.component("VisibleTransition", VisibleTransition);

export default Vue.extend({
	name: "CForm",
	components: {
		/**
		 * The components below represent what can/should appear in a form template generated by the server.
		 **/
		CPageProgress: () => import(/* webpackChunkName: "PageProgress" */ "./PageProgress.vue"),
		CRepeatingData: () => import(/* webpackChunkName: "RepeatingData" */ "./RepeatingData.vue"),
		CRepeatingSection: () => import(/* webpackChunkName: "RepeatingSection" */ "./RepeatingSection.vue"),
		CRepeatingTable: () => import(/* webpackChunkName: "RepeatingTable" */ "./RepeatingTable.vue"),
		CSection: () => import(/* webpackChunkName: "Section" */ "./Section.vue"),
		CInput: () => import(/* webpackChunkName: "Input" */ "./Input.vue"),
		CContent: () => import(/* webpackChunkName: "Input" */ "./Content.vue"),
		CName: () => import(/* webpackChunkName: "Name" */ "./Name.vue"),
		CAddress: () => import(/* webpackChunkName: "Address" */ "./Address.vue"),
		CSpinner: () => import(/* webpackChunkName: "Spinner" */ "./Spinner.vue"),
		CSlider: () => import(/* webpackChunkName: "Slider" */ "./Slider.vue"),
		CSelect: () => import(/* webpackChunkName: "Select" */ "./Select.vue"),
		CDatePicker: () => import(/* webpackChunkName: "DatePicker" */ "./DatePicker.vue"),
		CTimePicker: () => import(/* webpackChunkName: "TimePicker" */ "./TimePicker.vue"),
		CCheckboxGroup: () => import(/* webpackChunkName: "CheckboxGroup" */ "./CheckboxGroup.vue"),
		CChoiceGroup: () => import(/* webpackChunkName: "ChoiceGroup" */ "./ChoiceGroup.vue"),
		CCheckbox: () => import(/* webpackChunkName: "Checkbox" */ "./Checkbox.vue"),
		CRadioGroup: () => import(/* webpackChunkName: "RadioGroup" */ "./RadioGroup.vue"),
		CRadio: () => import(/* webpackChunkName: "Radio" */ "./Radio.vue"),
		CRatingScale: () => import(/* webpackChunkName: "RatingScale" */ "./RatingScale.vue"),
		CToggle: () => import(/* webpackChunkName: "Toggle" */ "./Toggle.vue"),
		CSignature: () => import(/* webpackChunkName: "Signature" */ "./Signature.vue"),
		CUpload: () => import(/* webpackChunkName: "Upload" */ "./Upload.vue"),
		CSaveResumeDialog: () => import(/* webpackChunkName: "SaveResumeDialog" */ "./SaveResumeDialog.vue"),
		CImagePicker: () => import(/* webpackChunkName: "ImagePicker" */ "./ImagePicker.vue"),
		CBranding: () => import(/* webpackChunkName: "Branding" */ "./Branding.vue"),
		CAbuse: () => import(/* webpackChunkName: "Abuse" */ "./Abuse.vue"),
		CConfirmation: () => import(/* webpackChunkName: "Confirmation" */ "./Confirmation.vue"),
		CPageNavigation: () => import(/* webpackChunkName: "PageNavigation" */ "./PageNavigation.vue")
	}
});